#!/usr/bin/env zsh
alias ls='ls --color=auto'
alias ll='ls -l'
alias lla='ls -la'

#function chpwd() { 
#    emulate -L zsh
#    ls -a
#}

alias dotconfig='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias grep='grep --color=auto'

nviml() {
    nvim -u $CONFIG/nvim/lightinit.vim $@
}

nman() {
    nviml -Rc "Man $@ | on" 
}

man() {
    LESS_TERMCAP_md=$'\e[01;35m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[48;5;7;38;5;16m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}


#if [[ $(command -v bat) ]]; then
#    alias bat='bat --theme GitHub'
#fi


lfcd () {
    tmp="$(mktemp)"
    /usr/local/bin/lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        if [ -d "$dir" ]; then
            if [ "$dir" != "$(pwd)" ]; then
                cd "$dir"
            fi
        fi
    fi
}

lf() {
    [[ $LF_LEVEL && (-z "$TMUX" || "$LF_LEVEL" > 1) ]] && exit || lfcd "$@"
}
#zle -N lf

#alias lf='lfcd'
alias topmem='ps axch ocmd:15,%mem | sort -uk 1.1,1.15 | sort -rk 1.16 | head'
alias topcpu='ps axch ocmd:15,%cpu | sort -uk 1.1,1.15 | sort -rk 1.16 | head'
alias expacsize="expac -S -H M '%kt %n'"
alias expacdate="expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort | tail"
alias dmenu="dmenu -nb #000000"
alias firefoxp="firefox --private-window"
