#!/usr/bin/env zsh

alias ls='ls --color=auto'
alias ll='ls -l'
alias lla='ls -la'

function chpwd() { 
    emulate -L zsh
    ls -a
}

alias dotconfig='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
