#!/bin/sh

delim="|"

setup() { \
	#pad the living shit out of this shit
	printf "%142c" " "
	free -m | awk '/^Mem:/ {print int($3 / 100) / 10 "/" int($2 / 100) / 10}'
	echo $delim
	date "+%d/%m %R"
}

while :; do
	xsetroot -name "$(setup | tr '\n' ' ')"
	sleep 10s & 
	wait
done
