#!/bin/sh
bspc rule -r "*"

bspc monitor $(xrandr | grep " connected " | awk '{ print$1 }') -d 1 2 3 4 5 6 7 8 9 10
bscp desktop -f 1 

bspc config border_width 1
bspc config window_gap 0
bspc config top_padding 24	
bspc config focus_follows_pointer true
bspc config focused_border_color $(xrdb -query | awk '/\*\.color13:/ {print $2}')
bspc config borderless_monocle  true
bspc config gapless_monocle true
bspc config single_monocle true

bspc rule -a Emacs state=tiled

$XDG_CONFIG_HOME/polybar/launch.sh &

setup() {
    until [ ! -s "/tmp/bspwm_$DISPLAY_0" ]; do # wait for socket
        sleep 1
    done

    bspc subscribe node_add node_remove node_focus desktop_focus | while read -r line
    do
        polybar-msg hook window-list 1
    done

    #bspc subscribe node_focus node_remove desktop_focus node_add | while read -r line
    #do
        #polybar-msg hook window-title 1
    #done
}

setup &
